const listOfPairs: CompoundWord[] = [
  ["christmas", "tree"],
  ["digestive", "schnapps"],
  ["christmas", "carol"],
  ["Santa", "Claus"],
  ["mulled", "wine"],
  ["gift", "exchange"],
  ["christmas", "present"],
  ["Family", "disputes"],
  ["consumption", "trap"],
  ["chocolate", "milk"],
  ["winter", "tires"],
  ["reindeer", "sleigh"],
  ["christmas", "decoration"],
  ["fairy", "lights"],
  ["mistletoe", "kiss"],
  ["santa", "claus"],
  ["north", "pole"],
  ["stomach", "pain"],
  ["holiday", "decoration"],
  ["social", "distancing"],
  ["road", "grit"],
  ["snow", "chaos"],
  ["christmas", "carols"],
  ["climate", "change"],
  ["epiphany", "kings"],
  ["hot", "chocolate"],
  ["anger", "management"],
  ["saint", "nicholas"],
  ["christmas", "stockings"],
  ["advent", "calendar"],
];

export default listOfPairs;
