const listOfPairs: [string, string][] = [
  ["bird", "cage"],
  ["birthday", "cake"],
  ["bubble", "wrap"],
  ["business", "suit"],
  ["car", "wash"],
  ["cash", "flow"],
  ["change", "request"],
  ["cheese", "cake"],
  ["coal", "mine"],
  ["coffee", "shop"],
  ["company", "car"],
  ["crossword", "puzzle"],
  ["doggy", "bag"],
  ["drug", "test"],
  ["elementary", "school"],
  ["flower", "garden"],
  ["fruit", "salad"],
  ["grass", "roots"],
  ["iron", "man"],
  ["lion", "king"],
  ["mobile", "phone"],
  ["money", "bag"],
  ["monkey", "wrench"],
  ["mountain", "bike"],
  ["photo", "shoot"],
  ["river", "flow"],
  ["shopping", "cart"],
  ["software", "package"],
  ["space", "ship"],
  ["taxi", "driver"],
  ["traffic", "light"],
  ["travel", "guide"],
  ["tv", "channel"],
  ["water", "cooler"]
];

export default listOfPairs;
